# Generated by Django 2.0.6 on 2018-12-08 15:47

import ckeditor_uploader.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atricles',
            name='backrich',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='atricles',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atricles',
            name='background',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='atricles',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='atricles',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
