# Generated by Django 2.1.4 on 2018-12-25 12:57

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20181208_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atricles',
            name='backrich',
        ),
        migrations.AddField(
            model_name='atricles',
            name='color',
            field=colorful.fields.RGBColorField(null=True),
        ),
    ]
