# Generated by Django 2.1.4 on 2018-12-25 15:30

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20181225_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textMain', models.CharField(max_length=20)),
                ('text1', models.CharField(max_length=20)),
                ('text2', models.CharField(max_length=20)),
                ('text3', models.CharField(max_length=20)),
                ('text4', models.CharField(max_length=20)),
                ('color', colorful.fields.RGBColorField(default='#f8f9fa')),
            ],
        ),
    ]
