# Generated by Django 2.1.4 on 2018-12-25 15:39

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_navbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='fontColor',
            field=colorful.fields.RGBColorField(default='#ffffff'),
        ),
    ]
