# Generated by Django 2.1.4 on 2018-12-25 16:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='text1',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='text2',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
