# Generated by Django 2.1.4 on 2018-12-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_basepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='text5',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
