# Generated by Django 2.1.4 on 2018-12-25 19:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_navbar_text5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atricles',
            name='author',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='atricles',
            name='date',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='atricles',
            name='text',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='atricles',
            name='title',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
