# Generated by Django 2.1.4 on 2018-12-25 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20181225_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atricles',
            old_name='color',
            new_name='backgroundColor',
        ),
    ]
