# Generated by Django 2.1.4 on 2018-12-25 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20181225_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='atricles',
            name='categoryId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Categories'),
        ),
    ]
