# Generated by Django 2.1.4 on 2018-12-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_categories_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
