# Generated by Django 2.1.4 on 2018-12-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20181225_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='atricles',
            name='isVisible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='atricles',
            name='isBest',
            field=models.NullBooleanField(default=False),
        ),
    ]
