# Generated by Django 2.1.4 on 2018-12-30 09:44

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20181229_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelDetails', tinymce.models.HTMLField(null=True)),
                ('labelPhone', tinymce.models.HTMLField(null=True)),
                ('phone', tinymce.models.HTMLField(null=True)),
                ('labelEmail', tinymce.models.HTMLField(null=True)),
                ('email', tinymce.models.HTMLField(null=True)),
            ],
        ),
    ]
