# Generated by Django 2.1.4 on 2018-12-30 10:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', tinymce.models.HTMLField(null=True)),
                ('contant', tinymce.models.HTMLField(null=True)),
            ],
        ),
    ]
