# Generated by Django 2.1.4 on 2018-12-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_aboutme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='contant',
            new_name='content',
        ),
    ]
