# Generated by Django 2.1.4 on 2019-01-10 19:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_logsignin_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsignin',
            name='date',
            field=models.TimeField(default=datetime.datetime(2019, 1, 10, 19, 32, 17, 131222, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='logsignin',
            name='isSuccess',
            field=models.BooleanField(default=False),
        ),
    ]
