# Generated by Django 2.1.4 on 2019-01-14 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_auto_20190110_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('date', models.TimeField(default=datetime.datetime(2019, 1, 14, 18, 39, 38, 130535, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='logsignin',
            name='date',
            field=models.TimeField(default=datetime.datetime(2019, 1, 14, 18, 39, 38, 129539, tzinfo=utc)),
        ),
    ]
